### ISSUE TITLE
Instructions to use local build

### ISSUE THREAD

**Issue by adarshraj93** [zariiii9003/autosar-e2e#3]
Hi, I was following the instructions to build the module locally and use it, but I feel it is complete. I am able to build to successfully but how do I import the local build into my python code?

**Comment by zariiii9003** [comment]
I'm not 100% sure, if i understood correctly, but if you use `pipx run build` then you'll have a `dist` folder in your current working directory. That folder contains the built source and binary distribution (`*.whl` file) which you can install with pip.

You could also download prebuilt binaries from [PyPI](https://pypi.org/project/autosar-e2e/#files).

**Comment by adarshraj93** [comment]
Sorry to sound like a noob. That's exactly what I wanted to know. I have the ` .whl` file build  but didn't know how to install it (think if you include that in the readme it would help people who are not very familiar with the process). 

I am working on a similar project implementing different kinds of CRCs and autosar profile5 in Cpp and trying to call it in python but had trouble talking between the two languages.  I really liked your implementation of the CRC and profile 2.  I see you are creating an Python object on you C file for the crc and profile 2 and ties to the module python during the build process. Could you highlight the libraries used so I can look up the documentation and understand more of your implementation?

**Comment by zariiii9003** [comment]
I see, i was a little confused on why you wouldn't just install it with pip from PyPI.

Regarding libraries: I didn't use any libraries actually. Using C extensions is a core feature of python. Take a look at the [docs here](https://docs.python.org/3/extending/extending.html). There's a pretty steep learning curve at first, at least that was my experience. But there are a few examples and you could use this repo as a starting point.

For the autosar related stuff i found documents via google. Their names are `AUTOSAR_PRS_E2EProtocol_R21-11.pdf` and `AUTOSAR_SWS_CRCLibrary_R21-11.pdf`.

Btw there is a [python implementation of profile 5 in cantools](https://github.com/cantools/cantools/blob/c053be19749e1cc7f7de864c9ee9a5670b711a46/cantools/autosar/end_to_end.py#L95). I didn't try that though.

**Comment by adarshraj93** [comment]
Thank you for the references. I agree, I did check this page and the learning curve is steep.  I didn't know cantools had the autosar profile implemented. Looks like they are the using crccheck module.

I am looking more at how you had implemented the integration as that is something I am trying to get at. The references you shared definitely helps my case.

**Comment by zariiii9003** [comment]
You could try this PR for Profile 5: #4

**Comment by adarshraj93** [comment]
Thank you @zariiii9003. I was able to implement profile 5 without this PR by calling the CRC16 function twice. It is the same as the PR implementation you have done.

Once you merge it, it will be easier to call just the p05 function once rather than my current implementation.

**Comment by zariiii9003** [comment]
I just uploaded version 0.4.0 with support for profile 5. Hope it works :)

**Comment by adarshraj93** [comment]
I will test it out and let you know. Thank you :)

**Comment by Memfispro** [comment]
Hello. How can I contact you? Do you have an email?

**Comment by adarshraj93** [comment]
@zariiii9003 this works. closing this issue  :) @Memfispro you can reach me at adarshbecoding@gmail.com
