### ISSUE TITLE
to implement profile 04

### ISSUE THREAD

**Issue by dayangshanbaoye** [zariiii9003/autosar-e2e#7]
can you help to implement profile4 in the autosar official document?
https://www.autosar.org/fileadmin/standards/R20-11/FO/AUTOSAR_PRS_E2EProtocol.pdf

**Comment by zariiii9003** [comment]
Try this branch: https://github.com/zariiii9003/autosar-e2e/tree/p04

**Comment by dayangshanbaoye** [comment]
It works, many thanks
